version: "3"

services:
  movie-catalog-service:
    container_name: movie-catalog-service
    build:
      context: movie-catalog-service
    ports:
      - 8090:8080
      - 5006:5005
  movie-info-service:
    container_name: movie-info-service
    build:
      context: movie-info-service
    ports:
      - 8091:8080
      - 5007:5005
  ratings-data-service:
    container_name: ratings-data-service
    build:
      context: ratings-data-service
    ports:
      - 8092:8080
      - 5008:5005
