version: '3'

services:
  postgres:
    image: postgres:14
    healthcheck:
      test: psql postgres --command "select 1" -U postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
  pact_broker:
    image: pactfoundation/pact-broker:2.101.0.1
    depends_on:
      - postgres
    ports:
      - "9090:9292"
    links:
      - postgres
    environment:
      PACT_BROKER_DATABASE_USERNAME: postgres
      PACT_BROKER_DATABASE_PASSWORD: password
      PACT_BROKER_DATABASE_HOST: postgres
      PACT_BROKER_DATABASE_NAME: postgres
      PACT_BROKER_WEBHOOK_SCHEME_WHITELIST: http https
      PACT_BROKER_WEBHOOK_HOST_WHITELIST: jenkins
  jenkins:
    build:
      context: jenkins
    ports:
      - "9091:8080"
      - "50000:50000"
    volumes:
      - ./jenkins/jenkins_home:/var/jenkins_home
      - ../:/continuous-consumer-contracts
      - ~/.m2/repository:/var/jenkins_home/.m2/repository

volumes:
  postgres:
